using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Vessel.Application.Files;
using Vessel.Application.Processes;
using Vessel.Application.Proxy;
using Vessel.Domain;
using Vessel.Domain.Proxy;
using ApplicationId = Vessel.Domain.ApplicationId;

namespace Vessel.Infrastructure.Proxy;

public sealed class TraefikProxyProvider(IProcessRunner processRunner, IPathSafetyService pathSafety) : IProxyProvider
{
    private static readonly Regex HostPattern = new("^[a-z0-9][a-z0-9.-]{0,251}[a-z0-9]$", RegexOptions.Compiled);
    private readonly string _rootDirectory = Path.Combine(AppContext.BaseDirectory, "proxy", "traefik");

    public ProxyConfigurationDocument Generate(ServerId serverId, IReadOnlyList<ProxyRoute> routes)
    {
        var version = DateTimeOffset.UtcNow.ToString("yyyyMMddHHmmss");
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by Vessel. Do not edit by hand.");
        builder.AppendLine("http:");
        builder.AppendLine("  routers:");

        foreach (ProxyRoute route in routes.OrderBy(route => route.Host, StringComparer.OrdinalIgnoreCase))
        {
            var name = RouteName(route);
            builder.AppendLine($"    {name}:");
            builder.AppendLine($"      rule: \"Host(`{route.Host}`)\"");
            builder.AppendLine($"      service: {name}");
            builder.AppendLine("      entryPoints:");
            builder.AppendLine(route.TlsEnabled ? "        - websecure" : "        - web");
            if (route.TlsEnabled)
            {
                builder.AppendLine("      tls:");
                builder.AppendLine("        certResolver: letsencrypt");
            }

            if (route.RedirectToCanonical && !route.Canonical)
            {
                builder.AppendLine("      middlewares:");
                builder.AppendLine($"        - {name}-canonical");
            }
        }

        builder.AppendLine("  services:");
        foreach (ProxyRoute route in routes.OrderBy(route => route.Host, StringComparer.OrdinalIgnoreCase))
        {
            var name = RouteName(route);
            builder.AppendLine($"    {name}:");
            builder.AppendLine("      loadBalancer:");
            builder.AppendLine("        servers:");
            builder.AppendLine($"          - url: \"http://{route.ServiceName}:{route.TargetPort}\"");
        }

        IEnumerable<IGrouping<ApplicationId, ProxyRoute>> routeGroups = routes.GroupBy(route => route.ApplicationId);
        var middlewareGroups = routeGroups
            .Select(group => new
            {
                CanonicalHost = group.FirstOrDefault(route => route.Canonical)?.Host,
                RedirectRoutes = group.Where(route => route.RedirectToCanonical && !route.Canonical).ToArray()
            })
            .Where(group => group.RedirectRoutes.Length > 0)
            .ToArray();
        if (middlewareGroups.Length > 0)
        {
            builder.AppendLine("  middlewares:");
            foreach (var group in middlewareGroups)
            {
                if (string.IsNullOrWhiteSpace(group.CanonicalHost))
                    throw new InvalidOperationException(
                        "Redirect-to-canonical routes require a canonical domain for the same application.");

                foreach (ProxyRoute route in group.RedirectRoutes.OrderBy(route => route.Host,
                             StringComparer.OrdinalIgnoreCase))
                {
                    var name = RouteName(route);
                    builder.AppendLine($"    {name}-canonical:");
                    builder.AppendLine("      redirectRegex:");
                    builder.AppendLine($"        regex: \"^https?://{Regex.Escape(route.Host)}(.*)\"");
                    builder.AppendLine($"        replacement: \"https://{group.CanonicalHost}$${{1}}\"");
                    builder.AppendLine("        permanent: true");
                }
            }
        }

        var contents = builder.ToString().ReplaceLineEndings("\n");
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(contents))).ToLowerInvariant();
        return new ProxyConfigurationDocument(serverId, ProxyProviderKind.Traefik, version, contents, hash, routes);
    }

    public ProxyValidationResult Validate(ProxyConfigurationDocument document)
    {
        var errors = new List<string>();
        if (document.Provider != ProxyProviderKind.Traefik)
            errors.Add("Proxy provider must be Traefik.");
        if (string.IsNullOrWhiteSpace(document.Contents))
            errors.Add("Proxy configuration is empty.");
        if (!document.Contents.Contains("http:", StringComparison.Ordinal) ||
            !document.Contents.Contains("routers:", StringComparison.Ordinal) ||
            !document.Contents.Contains("services:", StringComparison.Ordinal))
            errors.Add("Proxy configuration must include Traefik http routers and services.");
        if (document.Contents.Contains("BEGIN PRIVATE KEY", StringComparison.OrdinalIgnoreCase) ||
            document.Contents.Contains("password", StringComparison.OrdinalIgnoreCase))
            errors.Add("Proxy configuration contains secret-like content.");

        foreach (ProxyRoute route in document.Routes)
        {
            if (!HostPattern.IsMatch(route.Host))
                errors.Add($"Domain host '{route.Host}' is invalid.");
            if (route.TargetPort is < 1 or > 65535)
                errors.Add($"Domain host '{route.Host}' has an invalid target port.");
        }

        var duplicateHosts = document.Routes
            .GroupBy(route => route.Host, StringComparer.OrdinalIgnoreCase)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToArray();
        foreach (var duplicate in duplicateHosts)
            errors.Add($"Domain host '{duplicate}' is configured more than once.");

        return errors.Count == 0 ? ProxyValidationResult.Success : new ProxyValidationResult(false, errors);
    }

    public async Task<ProxyApplyResult> ApplyAsync(
        ProxyConfigurationDocument document,
        ProxyConfigurationDocument? previous,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var dynamicDirectory = pathSafety.EnsureOwnedRelativePath(_rootDirectory, "dynamic");
            Directory.CreateDirectory(dynamicDirectory);
            var target =
                pathSafety.EnsureOwnedRelativePath(dynamicDirectory, $"server-{document.ServerId.Value:N}.yml");
            var temp = target + ".tmp";
            await File.WriteAllTextAsync(temp, document.Contents, Encoding.UTF8, cancellationToken);
            File.Move(temp, target, true);
            ProxyApplyResult reload = await ReloadAsync(document.ServerId, cancellationToken);
            if (!reload.Succeeded && previous is not null)
                await RollbackAsync(previous, cancellationToken);
            return reload;
        }
        catch (Exception ex)
        {
            return new ProxyApplyResult(false, ex.Message);
        }
    }

    public async Task<ProxyApplyResult> ReloadAsync(ServerId serverId, CancellationToken cancellationToken = default)
    {
        ProcessResult result = await processRunner.RunTextAsync(new ProcessCommand(
            "docker",
            ["kill", "--signal=HUP", "vessel-proxy"],
            Timeout: TimeSpan.FromSeconds(20)), cancellationToken);
        if (result.Succeeded)
            return new ProxyApplyResult(true, "Traefik reloaded.");

        if (result.ExitInfo.ExitCode == 1 &&
            result.StandardError.Contains("No such container", StringComparison.OrdinalIgnoreCase))
            return new ProxyApplyResult(true, "Traefik dynamic configuration written; proxy container is not running.");

        return new ProxyApplyResult(false, result.StandardError.Trim());
    }

    public async Task<ProxyApplyResult> RollbackAsync(
        ProxyConfigurationDocument previous,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var dynamicDirectory = pathSafety.EnsureOwnedRelativePath(_rootDirectory, "dynamic");
            Directory.CreateDirectory(dynamicDirectory);
            var target =
                pathSafety.EnsureOwnedRelativePath(dynamicDirectory, $"server-{previous.ServerId.Value:N}.yml");
            await File.WriteAllTextAsync(target, previous.Contents, Encoding.UTF8, cancellationToken);
            return await ReloadAsync(previous.ServerId, cancellationToken);
        }
        catch (Exception ex)
        {
            return new ProxyApplyResult(false, ex.Message);
        }
    }

    private static string RouteName(ProxyRoute route)
    {
        string host = new(route.Host.Select(character => char.IsLetterOrDigit(character) ? character : '-').ToArray());
        return $"vessel-{route.ApplicationId.Value:N}-{host}"[..Math.Min(63, 39 + host.Length)];
    }
}
